### ISSUE TITLE
Sparkles show up in a line along right side?

### ISSUE THREAD

**Issue by MurphyMc** [MurphyMc/light-before-xmas#7]
I haven't seen this in the web version, but have seen it on iPhone, and @AbePralle has seen it somewhere too.

After you win and it's doing the sparkles on the star and the tree, sometimes sparkles show up along a roughly vertical line toward the right side (maybe about even with the rightmost part of the tree).

A first thing to do might be to narrow down whether they're tree or star sparkles.  I've never seen one with much color, so I'm guessing they're star sparkles.  But I think it'd be pretty easy to figure out which by turning one of them off or (probably better) make it really obvious which are which (e.g., make one of them much larger).

Another hint that they may be star sparkles is [this bit of code](https://github.com/MurphyMc/light-before-xmas/blob/master/Source/Main.rogue#L923).  I don't remember how this works, but that certainly looks suspicious.  It's using `tree_sparkle_map.size` as part of computing the position for star sparkles.  It seems possible this is a copy/paste error (pasting the tree sparkle code).  Not sure why it doesn't seem to show up on all platforms.  iPhone has a different aspect ratio.  Maybe it's off the edge on most systems or something?

**Comment by AbePralle** [comment]
Pushed a fix!

- Both star & tree sparkles were appearing at right and bottom edges of map
- RNG was e.g. Random.int32(0,map.size.x), which is inclusive of map.size.x
- Bitmap.get(x,y) returns 0 if OOB; when random # was on edge it read as 0/black/valid
- Random.int32(map.size.x) would be exclusive (0 to map.size.x-1)
- Simplified the whole thing to be (Random.xy * map.size).floor
- Also fixed a tree vs star sizing issue
